server:
    port: 8082
spring:
    datasource:
        url: jdbc:h2:./devdb
        username: sa
    jpa.hibernate:
        ddl-auto: update 
    jpa:
        properties:
            javax:
                persistence:
                    validation:
                        mode: none    
#spring:
  